name: Python Application Test with Github
on: [push]
jobs: 
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v1
        with: 
          python-version: 3.8
      - name: Install dependencies
        run: |
          make install
      - name: lint
        run: |
          make lint
      - name: Test with Pytest
        run: |
          make test
      - name: Format
        run: |
          make format
    
